# Scene with 2 spheres and bunny

threads       = 4
image         = "scene0.png"
width         = 512
height        = 512
background    = "black"
ambient_light = "white"

[default_material]
k_diffuse = 0.7
k_specular = 0.3
k_ambient = 0.1
n_shininess  = 30.0
color = "white"

[camera]
distance    = 3.0
fov_angle   = 56.0
location    = [0.0, 0.0, 3.0]
direction   = [0.0, 0.0, -1.0]
up          = [0.0, 1.0, 0.0]

[[lights]]
color       = "white"
position    = [4.0, 4.0, 9.0]

[objects]
type = "Group"

[[objects.items]]
type = "Transform"
transform = {type = "Translate", vector = [-1.0, 0.0, 0.0]}

  [objects.items.child]
  type = "Primitive"
  primitive = "Sphere"
  radius = 0.4
  center = [0.0, 0.0, 0.0]

[[objects.items]]
type = "Transform"
transform = {type = "Translate", vector = [1.0, 0.0, 0.0]}

  [objects.items.child]
  type = "Primitive"
  primitive = "Sphere"
  radius = 0.4
  center = [0.0, 0.0, 0.0]

[[objects.items]]
type = "Material"

  [objects.items.material]
  k_diffuse   = 0.7
  k_specular  = 0.3
  k_ambient   = 0.1
  n_shininess = 30.0
  color = "CornflowerBlue"

  [objects.items.child]
  type = "Transform"
  transform = {type = "Rotate", degrees = 25.0, axis = [0.0, 1.0, 0.0]}
  #child = {type = "Mesh", mesh = "models/icos.smf", shading = "flat"}
  child = {type = "Mesh", mesh = "models/bound-bunny_5k.smf", shading = "smooth"}
