# Scene with 2 spheres and bunny

image       = "scene0.png"
width       = 512
height      = 512
background  = "black"

[camera]
distance    = 3.0
fov_angle   = 56.0
location    = [0.0, 0.0, 3.0]
direction   = [0.0, 0.0, -1.0]
up          = [0.0, 1.0, 0.0]

[objects]
type = "Group"

[[objects.items]]
type = "Transform"
transform = {type = "Translate", vector = [-1.0, 0.0, 0.0]}

  [objects.items.child]
  type = "Primitive"
  primitive = "Sphere"
  radius = 0.4
  center = [0.0, 0.0, 0.0]

[[objects.items]]
type = "Transform"
transform = {type = "Translate", vector = [1.0, 0.0, 0.0]}

  [objects.items.child]
  type = "Primitive"
  primitive = "Sphere"
  radius = 0.4
  center = [0.0, 0.0, 0.0]

[[objects.items]]
type = "Transform"
transform = {type = "Rotate", degrees = -90.0, axis = [0.0, 1.0, 0.0]}
#child = {type = "Mesh", mesh = "models/icos.smf"}
child = {type = "Mesh", mesh = "models/bound-bunny_1k.smf"}
